# Generated by Django 6.0.7 on 2026-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('interest_field', models.CharField(max_length=100, verbose_name='زمینه مورد علاقه')),
                ('source_page', models.CharField(blank=True, default='', max_length=200, verbose_name='صفحه\u200cای که چت از آن شروع شده')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='بررسی شده توسط ادمین')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('age', models.PositiveIntegerField(verbose_name='سن')),
                ('monthly_budget', models.CharField(max_length=100, verbose_name='هزینه ماهیانه آموزش')),
                ('free_time', models.CharField(max_length=100, verbose_name='میزان زمان آزاد هفتگی')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره دوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره دوره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('interest_field', models.CharField(max_length=100, verbose_name='زمینه مورد علاقه')),
                ('source_page', models.CharField(blank=True, default='', max_length=200, verbose_name='صفحه\u200cای که چت از آن شروع شده')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='بررسی شده توسط ادمین')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('courses', models.TextField(verbose_name='دوره\u200cهایی که کاربر دارد')),
            ],
            options={
                'verbose_name': 'درخواست منتور',
                'verbose_name_plural': 'درخواست\u200cهای منتور',
                'ordering': ['-created_at'],
            },
        ),
    ]
