# Generated by Django 6.0.7 on 2026-08-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/', verbose_name='تصویر پروفایل')),
                ('bio', models.TextField(blank=True, verbose_name='درباره من')),
                ('interests', models.ManyToManyField(blank=True, related_name='interested_users', to='Courses.category', verbose_name='علاقه\u200cمندی\u200cها')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
            },
        ),
    ]
