# Generated by Django 6.0.7 on 2026-08-29 08:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('billing', 'Billing Question'), ('suggestion', 'Course Suggestion'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=20, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خرید اشتراک',
                'verbose_name_plural': 'خریدهای اشتراک',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بسته')),
                ('course_count', models.PositiveIntegerField(verbose_name='تعداد دوره قابل انتخاب')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح کوتاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بسته اشتراک',
                'verbose_name_plural': 'بسته\u200cهای اشتراک',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('recommend', models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], default='yes', max_length=10, verbose_name='پیشنهاد می\u200cکنید؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('instructor_name', models.CharField(max_length=150, verbose_name='مدرس')),
                ('instructor_bio', models.TextField(blank=True, verbose_name='درباره مدرس')),
                ('provider_name', models.CharField(blank=True, help_text='مثلا فرادرس، مکتب\u200cخونه، یوتیوب', max_length=150, verbose_name='پلتفرم/سایت منبع')),
                ('source_url', models.URLField(blank=True, verbose_name='لینک اصلی دوره')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='سطح')),
                ('origin', models.CharField(choices=[('domestic', 'Original Production'), ('translated', 'Translated/Subtitled')], default='domestic', max_length=20, verbose_name='منشا')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('original_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت قبل از تخفیف')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='تصویر')),
                ('color', models.CharField(blank=True, help_text='e.g. #4361ee', max_length=20, verbose_name='رنگ آیکون')),
                ('icon', models.CharField(blank=True, help_text='حرف/کاراکتر کوتاه', max_length=4, verbose_name='آیکون')),
                ('lessons', models.PositiveIntegerField(default=0, verbose_name='تعداد جلسات')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='ساعت محتوا')),
                ('curriculum', models.TextField(blank=True, help_text='هر خط یک سرفصل', verbose_name='سرفصل\u200cها')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='Courses.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='پیشرفت')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='Courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام در دوره',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها در دوره\u200cها',
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
