# Generated by Django 6.0.7 on 2026-09-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_transaction_contact_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=20, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='course',
            name='origin',
            field=models.CharField(choices=[('domestic', 'تولید داخل'), ('translated', 'ترجمه شده')], default='domestic', max_length=20, verbose_name='منشا'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ (تومان)'),
        ),
    ]
